version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0

jobs:
  build:
    docker:
      - image: circleci/node:lts
    executor: docker/docker
    steps:
      - checkout
      - node/install
      - run:
          name: Build the project
          command: |
            npm i --omit=dev
            npm run build
      - run:
          name: Build and push the Docker images
          command: |
            docker buildx create --name mybuilder
            docker buildx use mybuilder
            docker buildx inspect --bootstrap
            docker buildx build --platform linux/amd64,linux/arm64 -t helvio/api:latest --push .

workflows:
  build-and-publish:
    jobs:
      - build