jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            npm i --omit=dev
            npm run build
      - docker/build:
          context: .
          dockerfile: Dockerfile
          tags:
            - helvio/api:latest
            - helvio/api:${CIRCLE_SHA1:0:7}
            - helvio/api:${CIRCLE_TAG}
            - helvio/api:${CIRCLE_BRANCH}
            - helvio/api:latest-arm64
            - helvio/api:${CIRCLE_SHA1:0:7}-arm64
            - helvio/api:${CIRCLE_TAG}-arm64
            - helvio/api:${CIRCLE_BRANCH}-arm64
          build-args:
            ARCH: arm64,amd64
      - docker/push:
          image: helvio/api
          tag: latest